- name: create a volume on nectar
  os_volume:
    display_name: '{{volume.vol_name}}'
    size: '{{volume.vol_size}}'
    availability_zone: '{{availability_zone}}'
    wait: yes
    timeout: 600
    state: present #absent
  register: new_vol

- name: get volume id
  set_fact:
    os_vol_id: '{{new_vol.id}}'

- name: show message
  debug:
    msg: 'volume {{os_vol_id}} has been created'

