- hosts: swarminit
  gather_facts: true
  tasks:
    - name: remove the swarm manager
      become: yes
      docker_swarm:
        state: absent
        force: true
    - name: restart docker 
      become: yes
      raw: systemctl daemon-reload; systemctl restart docker
    - name: init a new swarm
      become: yes
      docker_swarm:
        state: present
      register: myswarm

- hosts: swarmjoin
  gather_facts: true
  tasks:
    - name: remove the swarm swarm worker
      become: yes
      docker_swarm:
        state: absent
    - name: restart docker 
      become: yes
      raw: systemctl daemon-reload; systemctl restart docker
    - name:
      set_fact:
        swarm_manager_ip: "{{groups['swarminit'][0]}}"
    - name:
      debug: 
        msg: "{{swarm_manager_ip}}" 
    - name: join nodes
      become: yes
      docker_swarm:
        state: join
        advertise_addr: eth0:2377
        join_token: "{{hostvars[swarm_manager_ip]['myswarm']['swarm_facts']['JoinTokens']['Worker']}}"
        remote_addrs: [ "{{swarm_manager_ip}}:2377" ]

- hosts: swarminit
  gather_facts: true
  tasks:
    - name: copy the docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
    - name: start the couchdb service
      become: yes
      raw: docker stack deploy -c /home/ubuntu/docker-compose.yml mytest
  


      