version: "3"
services:
  master_db:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
      - "5986:5896"
      - "4369:4369"
      - "9100-9200:9100-9200"
    links:
      - dbserver-1
      - dbserver-2
    volumes:
      - /home/ubuntu/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: '123456'
      COUCHDB_SECRET: 'mysecret'
      NODENAME: '172.26.38.88'
    container_name: master_db
    networks:
      - mydbnet

  dbserver-1:
    image: couchdb
    restart: always
    ports:
      - "15984:5984"
      # - "15986:5896"
      # - "4369:4369"
      # - "9100-9200:9100-9200"
    volumes:
      - /home/ubuntu/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: '123456'
      COUCHDB_SECRET: 'mysecret'
      NODENAME: '172.26.36.180'
    container_name: dbserver-1
    networks:
      - mydbnet
  dbserver-2:
    image: couchdb
    restart: always
    ports:
      - "25984:5984"
      # - "25986:5896"
      # - "4369:4369"
      # - "9100-9200:9100-9200"
    volumes:
      - /home/ubuntu/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: '123456'
      COUCHDB_SECRET: 'mysecret'
      NODENAME: '172.26.38.67'
    container_name: dbserver-2
    networks:
      - mydbnet

networks:
  mydbnet: