- name: create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    key_name: '{{ item.key_name }}'
    flavor: '{{ item.flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ os_vol_id }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instances

- name: show instances
  debug:
    msg: "instances {{item.openstack.name}} has been created, ip address is {{item.openstack.public_v4}}"
  loop: '{{os_instances.results}}'
  when: item.openstack is defined


