- name: attach a volume
  hosts: localhost
  tasks:
    - name: attach volume to host
      os_server_volume:
        state: present
        server: CCCalan-ins4
        volume: demo-vol-1
        device: /dev/vdb


