- hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: true

  roles:
    - role: common
    #- role: openstack-images
    - role: volumes
    - role: security_groups
    - role: instances