- name: create volumes on nectar
  os_volume:
    display_name: '{{item.vol_name}}'
    size: '{{item.vol_size}}'
    availability_zone: '{{availability_zone}}'
    wait: yes
    timeout: 600
    state: present #absent
  loop: '{{ volumes }}'
  register: os_vol

- name: get volume ids
  set_fact:
    os_vol_ids: '{{os_vol_ids|default([]) + [ item.id ] }}' 
  loop: '{{ os_vol.results }}'

- name: show message
  debug:
    msg: 'volume {{os_vol_ids}} has been created'

