version: "3"
services:
  mydb:
    image: couchdb
    deploy:
      mode: global
    ports:
      - "5984:5984"
      - "5986:5896"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data:/data
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: '123456'
    networks:
      - mydbnet
networks:
  mydbnet: