- hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: true

  tasks:
    # - name: try
    #   raw: touch test.hl; rm test.hl
    - name: get servers
      os_server_facts:
    - name: show
      debug:
        msg: '{{openstack_servers}}'

